config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :trips
    resources :vehicles

    root to: 'users#index'
  end
  resources :trips do
    collection do
      get 'enter_time'
    end
  end
  devise_for :users, skip: [:registration]
  root to: 'static#homepage'
end

app/models/trip.rb
# frozen_string_literal: true

class Trip < ApplicationRecord
  has_one_attached :signature
  has_one :user
  has_one :vehicle

  enum status: { entered: 0, scheduled: 1, completed: 2, billed: 3, locked: 4 }
  validates :first_name, :last_name, :pickup_address, :pickup_city, :pickup_zip, :delivery_address, :delivery_city, presence: true
  before_save :normalize_blank_values, :set_trip_status

  scope :assigned_to, ->(user) { where(user_id: user.id) unless (user.role & %w[dispatch admin]).present? }
  scope :scheduled_on, ->(date) { where(scheduled_pickup_date: date) }
  scope :with_driver, ->(user_id) { where(user_id: user_id) }

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def has_notes
    tool_tip_generator
  end

  def update_status
    set_trip_status
  end

  private

  def set_trip_status
    if entered?
      scheduled! unless scheduled_pickup_time.nil? || user_id.nil?
    end
    if scheduled?
      completed! unless scheduled_pickup_time.nil? || user_id.nil? || actual_pickup_time.nil? || departure_time.nil? || actual_dropoff_time.nil? || !signature.attached?
    end
    if scheduled?
      entered! if scheduled_pickup_time.nil? || user_id.nil?
    end
  end

  def tool_tip_generator
    if special_needs.nil? && instructions.nil?
      nil
    elsif special_needs.nil?
      "<h5>Instructions</h5> <p>#{instructions}</p>"
    elsif instructions.nil?
      "<h5>Special Needs</h5><p>#{special_needs}</p>"
    else
      "<h5>Special Needs</h5><p>#{special_needs}</p> <br/> <h5>Instructions</h5> <p>#{instructions}</p>"
    end
  end

  def normalize_blank_values
    attributes.each do |column, _value|
      self[column].present? || self[column] = nil
    end
  end
end

app/controllers/admin/trips_controller.rb
module Admin
  class TripsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Trip.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Trip.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/trips_controller.rb
# frozen_string_literal: true

# Controller handles all Trip actions
class TripsController < ApplicationController
  before_action :set_trip, only: %i[show edit update]
  before_action :filter_blank_time_fields, only: %i[create update]

  def index
    @date = trip_search_params[:date]
    @driver_id = trip_search_params[:driver_id]

    query = Trip.order(:scheduled_pickup_time).assigned_to(current_user)
    query = query.with_driver(@driver_id) if @driver_id.present?
    query = query.scheduled_on(@date.to_date) if @date.present?

    @trips = query

    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def enter_time
    @trips = Trip.order(:scheduled_pickup_time).assigned_to(current_user)
  end

  def new
    @trip = Trip.new
    authorize @trip
  end

  def create
    @trip = Trip.new(permitted_attributes(Trip))

    if @trip.save
      redirect_to @trip, notice: 'Trip saved successfully'
    else
      render :new
    end
  end

  def show; end

  def edit
    authorize @trip
  end

  def update
    respond_to do |format|
      if trip_params.key?(:signature)

        data_uri = trip_params[:signature]
        encoded_image = data_uri.split(',')[1]
        decoded_image = Base64.decode64(encoded_image)
        filename = 'signature.png'
        tmp_file = Tempfile.new(filename)
        tmp_file.binmode
        tmp_file.write(decoded_image)
        tmp_file.rewind

        @trip.signature.attach(io: tmp_file, filename: filename)

        tmp_file.unlink

        @trip.update_status
        format.html { redirect_to :trips }
      end

      if !trip_params.key?(:signature) && @trip.update(trip_params)
        if current_user.role.include?('driver')
          format.html { redirect_to :edit_trip }
        else
          format.js
          format.html { redirect_to @trip }
        end
      else
        format.html { render :edit }
      end
    end
  end

  private

  def trip_params
    params.require(:trip).permit(policy(@trip).permitted_attributes)
  end

  def trip_search_params
    params.permit(:date, :driver_id)
  end

  def set_trip
    @trip = Trip.find(params[:id])
  end

  def filter_blank_time_fields
    time_fields = %w[scheduled_pickup_time actual_pickup_time departure_time actual_dropoff_time]
    time_inputs = %w[(1i) (2i) (3i) (4i) (5i)]

    time_fields.each do |field|
      next if params[:trip]["#{field}(4i)"].nil?
      next unless params[:trip]["#{field}(4i)"].blank?

      time_inputs.each do |input|
        params[:trip]["#{field}#{input}"] = ''
      end
    end
  end
end

app/helpers/trips_helper.rb
# frozen_string_literal: true

module TripsHelper
  def status_label(status)
    status_span_generator status
  end

  def build_url(trip, type)
    url = 'https://www.google.com/maps/search/?api=1&query='
    query =
      if type == 'pickup'
        "#{trip.pickup_address}, #{trip.pickup_city}, #{trip.pickup_zip}"
      else
        "#{trip.delivery_address}, #{trip.delivery_city}"
      end

    url + CGI.escape(query)
  end

  def assigned_driver(user_id)
    User.find_by_id(user_id) ? User.find_by_id(user_id).name : 'Not assigned'
  end

  private

  def status_span_generator(status)
    case status
    when 'entered'
      content_tag(:span, status.capitalize, class: 'badge badge-warning')
    when 'scheduled'
      content_tag(:span, status.capitalize, class: 'badge badge-primary')
    when 'completed'
      content_tag(:span, status.capitalize, class: 'badge badge-success')
    end
  end
end

app/views/trips/_dispatch_index.html.erb
<div class="container mt-3">
  <div class="row">
    <%= form_with method: :get, local: true do |f| %>
      <%= f.date_field :date, value: @date, onchange: 'this.form.submit()' %>
      <%= f.collection_select :driver_id, User.is_driver, :id, :name, { selected: @driver_id, include_blank: true }, { onchange: 'this.form.submit()' } %>
    <% end %>
    <%= link_to 'Create Schedule', trips_path(format: :xlsx), class: "btn btn-sm btn-outline-primary ml-2" %>
  </div>
</div>
<div class="mt-3">
  <table class="table table-sm table-hover">
    <thead>
      <tr>
        <th>
          Status
        </th>
        <th>
          Driver
        </th>
        <th>
          Passenger
        </th>
        <th>
          Pickup Address
        </th>
        <th>
          Dropoff Address
        </th>
        <th>
          Phone Number
        </th>
        <th>
          Scheduled Pickup Time
        </th>
        <th>
          Appointment Date
        </th>
        <th>
          Vehicle Type
        </th>
        <th>
          Trip Reason
        </th>
        <th>
          Mileage
        </th>
        <th>
        </th>
        <th>
        </th>
        <th>
        </th>
      </tr>
    </thead>
    <tbody id="trips-listing">
      <%= render @trips %>
    </tbody>
  </table>
</div>

app/views/trips/_driver_edit.html.erb
<%= form_for trip do |f| %>
  <% if trip.errors.any?  %>
    <% trip.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: 'Scheduler Notification', sticky: false)  %>
    <% end %>
  <% end %>
  <% time = next_time_needed(trip) %>
  <div class="row">
    <div class='col'>
      <div class="row mt-5">
        <div class="form-group">
          <% if time == :signature %>
            <canvas id="canvas"></canvas>
            <%= f.hidden_field time, class:"form-control", id: "signature-input"%>
          <% else %>
            <%= f.label time %>
            <%= f.time_select time, ampm: true, include_blank: true, class:"form-control"%>
          <% end %>
        </div>
      </div>
      <div class="row mt-3">
        <%= f.submit 'Save', class: 'btn btn-primary btn-block mt-3', id: 'driver_edit_submit' %>
      </div>
    </div>
  </div>
<% end %>

app/views/trips/_driver_index.html.erb
<div class="mt-3">
  <div class="table-responsive">
    <table class="table table-sm table-hover">
      <thead>
        <tr>
          <th>
            Passenger
          </th>
          <th>
            Pickup Address
          </th>
          <th>
            Dropoff Address
          </th>
          <th>
            Phone Number
          </th>
          <th>
            Scheduled Pickup Time
          </th>
          <th>
            Appointment Date
          </th>
          <th>
            Vehicle Type
          </th>
          <th>
            Mileage
          </th>
        </tr>
      </thead>
      <tbody id="trips-listing">
        <%= render partial: 'driver_trip', locals: { trips: @trips } %>
      </tbody>
    </table>
  </div>
</div>

app/views/trips/_driver_trip.html.erb
 <% trips.each do |trip| %>
  <tr>
    <td>
      <%= trip.full_name %>
    </td>
    <td>
      <%= link_to(trip.pickup_address, build_url(trip, 'pickup'), target: :_blank) %>
    </td>
    <td>
      <%= link_to(trip.delivery_address, build_url(trip, 'delivery'), target: :_blank) %>
    </td>
    <td>
      <%= trip.phone_number %>
    </td>
    <td>
      <%= trip.scheduled_pickup_time.to_s.empty? ? "Not Scheduled" : trip.scheduled_pickup_time.to_s(:time) %>
    </td>
    <td>
      <%= trip.appointment_time %>
    </td>
    <td>
      <%= trip.vehicle_type %>
    </td>
    <td>
      <%= trip.mileage %>
    </td>
  </tr>
<% end %>

app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>
  <% if @trip.errors.any?  %>
    <% @trip.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: 'Scheduler Notification', sticky: false)  %>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col">
      <%= f.text_field :provider, class:"form-control", placeholder: 'Provider' %>
    </div>
    <div class="col">
      <%= f.text_field :provider_status, class:"form-control", placeholder: 'Provider Status' %>
    </div>
    <div class="col">
      <%= f.text_field :trip_number, class:"form-control", placeholder: 'Trip Number' %>
    </div>
    <div class="col">
      <%= f.text_field :reason_code, class:"form-control", placeholder: 'Reason Code' %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <%= f.text_field :first_name, class:"form-control", placeholder: 'First Name' %>
    </div>
    <div class="col">
      <%= f.text_field :last_name, class:"form-control", placeholder: 'Last Name' %>
    </div>
    <div class="col">
      <%= f.text_field :phone_number, class:"form-control", placeholder: 'Phone Number' %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <%= f.text_field :pickup_address, class:"form-control", placeholder: 'Pick Up Address' %>
    </div>
    <div class="col">
      <%= f.text_field :pickup_city, class:"form-control", placeholder: 'Pick Up City' %>
    </div>
    <div class="col">
      <%= f.text_field :pickup_zip, class:"form-control", placeholder: 'Pick Up Zip' %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <%= f.text_field :delivery_address, class:"form-control", placeholder: 'Drop Off Address' %>
    </div>
    <div class="col">
      <%= f.text_field :delivery_city, class:"form-control", placeholder: 'Drop Off City' %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <%= f.text_field :appointment_date, class:"form-control", placeholder: 'Appointment Date' %>
    </div>
    <div class="col">
      <%= f.text_field :appointment_time, class:"form-control", placeholder: 'Appointment Time' %>
    </div>
    <div class="col">
      <%= f.text_field :vehicle_type, class:"form-control", placeholder: 'Vehicle Type' %>
    </div>
    <div class="col">
      <%= f.text_field :trip_type, class:"form-control", placeholder: 'Trip Type' %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <%= f.text_field :additional_passengers, class:"form-control", placeholder: 'Additional Passengers' %>
    </div>
    <div class="col">
      <%= f.text_field :additional_appointments, class:"form-control", placeholder: 'Additional Appointments' %>
    </div>
    <div class="col">
      <%= f.number_field :mileage, class:"form-control", placeholder: 'Mileage' %>
    </div>
    <div class="col">
      <%= f.number_field :cost, class:"form-control", placeholder: 'Cost' %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col form-group">
      <%= f.label :scheduled_pickup_time %>
      <%= f.time_select :scheduled_pickup_time, minute_step: 5, include_blank: true, ampm: true, class:"form-control" %>
    </div>
    <div class="col form-group">
      <%= f.label :actual_pickup_time %>
      <%= f.time_select :actual_pickup_time, ampm: true, include_blank: true, class:"form-control"%>
    </div>
  </div>
  <div class="row mt-1">
    <div class="col form-group">
      <%= f.label :departure_time %>
      <%= f.time_select :departure_time, ampm: true, include_blank: true, class:"form-control" %>
    </div>
    <div class="col form-group">
      <%= f.label :actual_dropoff_time %>
      <%= f.time_select :actual_dropoff_time, ampm: true, include_blank: true, class:"form-control" %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <%= f.collection_select :user_id, User.order(:first_name), :id, :first_name, include_blank: true, class:"form-control" %>
    </div>
    <div class="col">
      <%= f.collection_select :vehicle_id, Vehicle.order(:vehicle_number), :id, :vehicle_number, include_blank: true, class:"form-control" %>
    </div>
    <div class="col">
      <%= f.select :signature_type, ['M', 'P', 'C'], include_blank: true, class:"form-control" %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <%= f.text_area :special_needs, class:"form-control", placeholder: 'Special Needs' %>
    </div>
    <div class="col">
      <%= f.text_area :instructions, class:"form-control", placeholder: 'Additional Instructions' %>
    </div>
  </div>
  <%= render partial: 'status', locals: { f: f } if policy(@trip).update? %>
  <div class="row mt-3">
    <div class="col">
      <%= f.submit 'Save', class: 'btn btn-primary btn-block mt-3' %>
    </div>
  </div>
<% end %>

app/views/trips/_scheduled_pickup.html.erb
<% if policy(trip).new? && (trip.entered? || trip.scheduled?) %>
  <%= form_with model: trip, method: :put do |f| %>
    <%= f.time_select :scheduled_pickup_time, {include_blank: true, minute_step: 5, ampm: true}, {id: "index-pickup-select-#{trip.id}", onchange: 'Rails.fire(this.form, "submit")'} %>
  <% end %>
<% else %>
  <%= trip.scheduled_pickup_time.to_s.empty? ? "Not Scheduled" : trip.scheduled_pickup_time.to_s(:time) %>
<% end %>

app/views/trips/_select_driver.html.erb
<% if policy(trip).new? && (trip.entered? || trip.scheduled?) %>
  <%= form_with model: trip, method: :put do |f| %>
    <%= f.collection_select :user_id, User.is_driver, :id, :name, {include_blank: true}, {id: "index-driver-select-#{trip.id}", onchange: 'Rails.fire(this.form, "submit")'} %>
  <% end %>
<% else %>
  <%= assigned_driver(trip.user_id) %>
<% end %>

app/views/trips/_status.html.erb
<div class="row mt-3">
  <div class="col">
    <div class="form-check form-check-inline">
      <%= f.radio_button :status, 'entered', class:"form-check-input" %>
      <%= f.label :entered, class:"form-check-label" %>
    </div>
    <div class="form-check form-check-inline">
      <%= f.radio_button :status, 'scheduled', class:"form-check-input" %>
      <%= f.label :scheduled, class:"form-check-label" %>
    </div>
    <div class="form-check form-check-inline">
      <%= f.radio_button :status, 'completed', class:"form-check-input" %>
      <%= f.label :completed, class:"form-check-label" %>
    </div>
    <div class="form-check form-check-inline">
      <%= f.radio_button :status, 'billed', class:"form-check-input" %>
      <%= f.label :billed, class:"form-check-label" %>
    </div>
    <div class="form-check form-check-inline">
      <%= f.radio_button :status, 'locked', class:"form-check-input" %>
      <%= f.label :locked, class:"form-check-label" %>
    </div>
  </div>
</div>

app/views/trips/_trip.html.erb
<tr>
  <td>
    <%= status_label(trip.status) %>
  </td>
  <td>
    <%= render partial: 'select_driver', locals: { trip: trip }  %>
  </td>
  <td>
    <%= trip.full_name %>
  </td>
  <td>
    <%= link_to(trip.pickup_address, build_url(trip, 'pickup'), target: :_blank) %>
  </td>
  <td>
    <%= link_to(trip.delivery_address, build_url(trip, 'delivery'), target: :_blank) %>
  </td>
  <td>
    <%= trip.phone_number %>
  </td>
  <td>
    <%= render partial: 'scheduled_pickup', locals: { trip: trip }  %>
  </td>
  <td>
    <%= trip.appointment_time %>
  </td>
  <td>
    <%= trip.vehicle_type %>
  </td>
  <td>
    <%= trip.reason_code %>
  </td>
  <td>
    <%= trip.mileage %>
  </td>
  <td>
    <%= link_to octicon("report", height: 24), trip_path(trip), data: {toggle:"tooltip", placement:'left', title: trip.has_notes, html:true}, class: 'index-note-icon', id: "note_button_#{trip.id}" if trip.has_notes %>
  </td>
  <td>
    <%= link_to octicon("pencil", height: 24), edit_trip_path(trip), class: 'index-edit-icon', id: "edit_button_#{trip.id}" if policy(trip).update? %>
  </td>
  <td>
    <%= link_to octicon("location", height: 24), trip_path(trip), class: 'index-edit-icon', id: "show_button_#{trip.id}" %>
  </td>
</tr>

app/views/trips/edit.html.erb
<div class="container">
  <h1 class="mt-2">Edit Trip</h1>
  <% if (current_user.role & %w[dispatch admin]).present? %>
    <%= render 'form'  %>
  <% else %>
    <%= render partial: 'driver_edit', locals: { trip: @trip }  %>
  <% end %>
</div>

app/views/trips/enter_time.html.erb
<div class="container mt-3">
  <div class="row">
    <%= form_with method: :get, local: true do |f| %>
      <%= f.date_field :date, value: @date, onchange: 'this.form.submit()' %>
      <%= f.collection_select :driver_id, User.is_driver, :id, :name, { selected: @driver_id, include_blank: true }, { onchange: 'this.form.submit()' } %>
    <% end %>
    <%= link_to 'Create Schedule', trips_path(format: :xlsx), class: "btn btn-sm btn-outline-primary ml-2" %>
  </div>
</div>
<div class="mt-3">
  <table class="table table-sm table-hover">
    <thead>
      <tr>
        <th>
          Passenger
        </th>
        <th>
          Pickup Address
        </th>
        <th>
          Dropoff Address
        </th>
        <th>
          Scheduled Pickup Time
        </th>
        <th>
          Actual Pickup Time
        </th>
        <th>
          Departure Time
        </th>
        <th>
          Dropoff Time
        </th>
      </tr>
    </thead>
    <tbody id="trips-listing">
      <% @trips.each do |trip| %>
        <tr>
          <td>
            <%= trip.full_name %>
          </td>
          <td>
            <%= link_to(trip.pickup_address, build_url(trip, 'pickup'), target: :_blank) %>
          </td>
          <td>
            <%= link_to(trip.delivery_address, build_url(trip, 'delivery'), target: :_blank) %>
          </td>
          <td>
            <%= trip.scheduled_pickup_time.to_s.empty? ? "Not Scheduled" : trip.scheduled_pickup_time.to_s(:time) %>
          </td>
          <%= form_for trip do |f| %>
            <td>
              <%= f.time_select :actual_pickup_time, ampm: true, include_blank: true, class:"form-control"%>
            </td>
            <td>
              <%= f.time_select :departure_time, ampm: true, include_blank: true, class:"form-control"%>
            </td>
            <td>
              <%= f.time_select :actual_dropoff_time, ampm: true, include_blank: true, class:"form-control"%>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/trips/index.html.erb
<% if (current_user.role & %w[dispatch admin]).present? %>
  <%= render partial: 'dispatch_index' %>
<% else %>
  <div class="mt-3">
    <%= render partial: 'driver_index', locals: { trips: @trips }  %>
  </div>
<% end %>

app/views/trips/new.html.erb
<h1>Create New Trip</h1>
<%= render 'form'  %>

app/views/trips/show.html.erb
<h2>Trip Detail</h2>
<div class="col-md-3 card card-body bg-light">
  <div class="show-trip-item">
    <span class="show-trip-label"> Driver: </span>
    <span class="show-trip-value">
      <%= User.find_by_id(@trip.user_id) ? User.find_by_id(@trip.user_id).name : 'Not assigned' %>
    </span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> Provider: </span>
    <span class="show-trip-value"> <%= @trip.provider %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> Provider_status: </span>
    <span class="show-trip-value"> <%= @trip.provider_status %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> trip_number: </span>
    <span class="show-trip-value"> <%= @trip.trip_number %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> first_name: </span>
    <span class="show-trip-value"> <%= @trip.first_name %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> last_name: </span>
    <span class="show-trip-value"> <%= @trip.last_name %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> phone_number: </span>
    <span class="show-trip-value"> <%= @trip.phone_number %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> pickup_address: </span>
    <span class="show-trip-value"> <%= @trip.pickup_address %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> pickup_city: </span>
    <span class="show-trip-value"> <%= @trip.pickup_city %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> pickup_zip: </span>
    <span class="show-trip-value"> <%= @trip.pickup_zip %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> delivery_address: </span>
    <span class="show-trip-value"> <%= @trip.delivery_address %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> delivery_city: </span>
    <span class="show-trip-value"> <%= @trip.delivery_city %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> appointment_date: </span>
    <span class="show-trip-value"> <%= @trip.appointment_date %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> appointment_time: </span>
    <span class="show-trip-value"> <%= @trip.appointment_time %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> reason_code: </span>
    <span class="show-trip-value"> <%= @trip.reason_code %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> vehicle_type: </span>
    <span class="show-trip-value"> <%= @trip.vehicle_type %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> trip_type: </span>
    <span class="show-trip-value"> <%= @trip.trip_type %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> additional_passengers: </span>
    <span class="show-trip-value"> <%= @trip.additional_passengers %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> additional_appointments: </span>
    <span class="show-trip-value"> <%= @trip.additional_appointments %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> mileage: </span>
    <span class="show-trip-value"> <%= @trip.mileage %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> cost: </span>
    <span class="show-trip-value"> <%= @trip.cost %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> special_needs: </span>
    <span class="show-trip-value"> <%= @trip.special_needs %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> instructions: </span>
    <span class="show-trip-value"> <%= @trip.instructions %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> signature_type: </span>
    <span class="show-trip-value"> <%= @trip.signature_type %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> scheduled_pickup_date: </span>
    <span class="show-trip-value"> <%= @trip.scheduled_pickup_date %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> scheduled_pickup_time: </span>
    <span class="show-trip-value"> <%= @trip.scheduled_pickup_time %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> actual_pickup_time: </span>
    <span class="show-trip-value"> <%= @trip.actual_pickup_time %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> departure_time: </span>
    <span class="show-trip-value"> <%= @trip.departure_time %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> actual_dropoff_time: </span>
    <span class="show-trip-value"> <%= @trip.actual_dropoff_time %></span>
  </div>
  <div class="show-trip-item">
    <span class="show-trip-label"> signature: </span>
    <span class="show-trip-value"> <%= image_tag @trip.signature %></span>
  </div>
</div>
<%= link_to 'Edit', edit_trip_path(@trip), class: 'btn btn-primary mt-4' if policy(@trip).update? %>